//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_ORDER
    {
        public O_ORDER()
        {
            this.D_ORDER_DETAIL = new HashSet<D_ORDER_DETAIL>();
        }
    
        public long ORDER_CD { get; set; }
        public string ORDER_CODE { get; set; }
        public string ORDER_CONTENT { get; set; }
        public Nullable<long> EMPLOYEE_CD { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<D_ORDER_DETAIL> D_ORDER_DETAIL { get; set; }
        public virtual M_EMPLOYEE M_EMPLOYEE { get; set; }
    }
}
