CREATE PROCEDURE [dbo].[SP_STATISTICS_VISIT]
AS
BEGIN
	DECLARE @COUNTER_VISIT_GN bigint
	DECLARE @Count int
	SELECT @Count=Count(*) FROM S_STATISTICS_VISIT ttk
	IF @Count IS NULL SET @Count=0
	IF @Count=0
		INSERT INTO S_STATISTICS_VISIT(TIME_ONLINE,COUNTER_VISIT)
		VALUES (GetDate(),1)
	ELSE
		BEGIN
			
			DECLARE @TIME_ONLINE_GN datetime
			SELECT @COUNTER_VISIT_GN=ttk.COUNTER_VISIT, @TIME_ONLINE_GN=ttk.TIME_ONLINE
			  FROM S_STATISTICS_VISIT ttk WHERE ttk.CD=(SELECT Max(ttk2.CD) FROM S_STATISTICS_VISIT ttk2)
			IF @COUNTER_VISIT_GN IS NULL SET @COUNTER_VISIT_GN=0
			IF @TIME_ONLINE_GN IS NULL SET @TIME_ONLINE_GN=getdate()
			-- Kiểm tra xem lần truy cập này có phải đã sang ngày mới không (Qua thời điểm 12h00)
			-- Nếu chưa sang ngày mới thì cập nhật lại COUNTER_VISIT
			IF Day(@TIME_ONLINE_GN)=Day(GETDATE())
				BEGIN
					UPDATE S_STATISTICS_VISIT
					SET
						COUNTER_VISIT = @COUNTER_VISIT_GN+1,
						TIME_ONLINE = GetDate()
						
					WHERE CD=(SELECT Max(ttk2.CD) FROM S_STATISTICS_VISIT ttk2)
				END
				-- Nếu đã sang ngày mới thì thêm mới bản ghi, COUNTER_VISIT bắt đầu lại là 1
			ELSE
				BEGIN
					INSERT INTO S_STATISTICS_VISIT(TIME_ONLINE, COUNTER_VISIT)
					VALUES (GetDate(),1)
				END
		END
 
		-- Thống kê Hom nay, Hom qua, Tuan nay, Tuan Truoc, Thang nay, Thang Truoc
		DECLARE @TODAY INT
		SET @TODAY = datepart(dw, GetDate())
		SELECT @COUNTER_VISIT_GN=ttk.COUNTER_VISIT, @TIME_ONLINE_GN=ttk.TIME_ONLINE
			  FROM S_STATISTICS_VISIT ttk WHERE ttk.CD=(SELECT Max(ttk2.CD) FROM S_STATISTICS_VISIT ttk2)
		--Tính COUNTER_VISITHomQua
		DECLARE @COUNTER_VISIT_HQ bigint
		SELECT @COUNTER_VISIT_HQ=isnull(COUNTER_VISIT,0) FROM S_STATISTICS_VISIT  
			WHERE CONVERT(nvarchar(20),TIME_ONLINE,103)=CONVERT(nvarchar(20),GETDATE()-1,103)
		IF @COUNTER_VISIT_HQ IS null SET @COUNTER_VISIT_HQ=0
		-- Tính Ngày đầu tuần này
		DECLARE @WEEK_TN datetime
		SET @WEEK_TN= DATEADD(wk, DATEDIFF(wk, 6, GetDate()), 6)
		-- Tính Ngày đầu của tuần trước Tính từ thời điểm 00:00:))
		DECLARE @WEEK_NDTT datetime
		SET @WEEK_NDTT = Cast(CONVERT(nvarchar(30),DATEADD(dd, -(@TODAY+6), GetDate()),101) AS datetime)
		-- Tính ngày cuối tuần trước tính đến 24h ngày cuối tuần 
		DECLARE @WEEK_NCTT datetime
		SET @WEEK_NCTT = Cast(CONVERT(nvarchar(30),DATEADD(dd, -@TODAY, GetDate()),101) +' 23:59:59' AS datetime)
		
		-- Tính số truy cập tuần này
		DECLARE @COUNTER_VISIT_WEEK_TN bigint
		SELECT @COUNTER_VISIT_WEEK_TN=isnull(Sum(COUNTER_VISIT),0) FROM S_STATISTICS_VISIT ttk 
			WHERE ttk.TIME_ONLINE BETWEEN @WEEK_TN AND getdate()
		 
		-- Tính số truy cập tuần trước
		DECLARE @COUNTER_VISIT_WEEK_TT bigint
		SELECT @COUNTER_VISIT_WEEK_TT=isnull(sum(COUNTER_VISIT),0)  FROM S_STATISTICS_VISIT ttk 
			WHERE ttk.TIME_ONLINE BETWEEN @WEEK_NDTT AND @WEEK_NCTT
		
		-- Tính số truy cập tháng này
		DECLARE @COUNTER_VISIT_MONTH_TN bigint 
		SELECT @COUNTER_VISIT_MONTH_TN=isnull(Sum(COUNTER_VISIT),0)
			FROM S_STATISTICS_VISIT ttk WHERE MONTH(ttk.TIME_ONLINE)=MONTH(GETDATE())
		
		-- Tính số truy cập tháng trước
		DECLARE @COUNTER_VISIT_MONTH_TT bigint 
		SELECT @COUNTER_VISIT_MONTH_TT=isnull(Sum(COUNTER_VISIT),0)
			FROM S_STATISTICS_VISIT ttk WHERE MONTH(ttk.TIME_ONLINE)=MONTH(GETDATE())-1
		
		-- Tính tổng số
		DECLARE @COUNTER_VISIT_TOTAL bigint
		SELECT  @COUNTER_VISIT_TOTAL=isnull(Sum(COUNTER_VISIT),0) FROM S_STATISTICS_VISIT ttk
		
		SELECT @COUNTER_VISIT_GN AS COUNTER_VISIT_GN, 
		@COUNTER_VISIT_HQ AS COUNTER_VISIT_HQ,
		@COUNTER_VISIT_WEEK_TN AS COUNTER_VISIT_WEEK_TN, 
		@COUNTER_VISIT_WEEK_TT AS COUNTER_VISIT_WEEK_TT, 
		@COUNTER_VISIT_MONTH_TN AS COUNTER_VISIT_MONTH_TN, 
		@COUNTER_VISIT_MONTH_TT AS COUNTER_VISIT_MONTH_TT,
		@COUNTER_VISIT_TOTAL AS COUNTER_VISIT_TOTAL
END