//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_CUSTOMER
    {
        public O_CUSTOMER()
        {
            this.O_ORDER = new HashSet<O_ORDER>();
            this.O_USER_CUSTOMER = new HashSet<O_USER_CUSTOMER>();
        }
    
        public long CUSTOMER_CD { get; set; }
        public string CUSTOMER_CODE { get; set; }
        public string CUSTOMER_NAME { get; set; }
        public string CUSTOMER_FIRST_NAME { get; set; }
        public string CUSTOMER_LAST_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public Nullable<long> STATUS { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
    
        public virtual ICollection<O_ORDER> O_ORDER { get; set; }
        public virtual ICollection<O_USER_CUSTOMER> O_USER_CUSTOMER { get; set; }
    }
}
