//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W_GJS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_PRICE_GOLD
    {
        public long PRICE_GOLD_CD { get; set; }
        public Nullable<decimal> PRICE_SALES { get; set; }
        public Nullable<decimal> PRICE_BUY { get; set; }
        public string GOLD_CODE { get; set; }
        public string GOLD_NAME { get; set; }
    }
}
